name: "Test"

on:
  push:
  pull_request:

jobs:
  nix:
    runs-on: macos-15-large
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        extra_nix_config: |
          substituters = https://cl-nix-lite.cachix.org https://cache.nixos.org/
          trusted-public-keys = cl-nix-lite.cachix.org-1:ab6+b0u2vxymMLcZ5DDqPKnxz0WObbMszmC+BDBHpFc= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: yangm97-mau
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
    - run: nix flake check -L

  nocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nobssoftware/nocommit@v1
        name: nocommit
